---
title: "Homework 2"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

Due: 3/8

Using the hw2 data on github answer the following questions. There are 7 waves of data, each with a different file (hw2-t1, hw2-t2, etc). There are five different types of repeated measures variables, all from "the Big Five" of personality. Each of these five constructs have 9 items associated with them. See codebook for more details. 


1. Your first task is to combine the datasets to create a longitudinal dataset. Then create composites of each of the 5 constructs and run growth models on each of these composite constructs. Include varying intercept and slopes for each of the five models. Bonus points for doing so in purrr. Interpret the parameters for 1 of the models that you are interested in. 

2. Introduce age and sex as predictors to the slope and intercept to the same model you interpreted in #1. Interpret each of the parameters.  
3. Use the output to create a table, suitable for publication in a journal. 

4. Plot the predicted fixed effects along with the random effects on the same plot. 

5. From the model created in #3, introduce one of the remaining 4 repeated measures as a time varying covariate (tvc) at level 1. First, run the model where the time varying covariate is constrained to be equal for everyone. Interpret the parameters of your model. 

6. Run a second tvc model where the new repeated measure is allowed to vary randomly across people. Interpret. Then compare this one with the one where it is constrained to be equal using a likelihood ratio test. Interpret.    

7. From the model created in #6, plot the fitted values with respect to time, controlling for the tvc. This should look similar to the plot in #4, with the difference that this plot controls for the TVC.  



