---
title: "syllabus"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

**Class hours** Monday and Wednesday 1-2:20  
**Instructor**: Joshua Jackson  
**Office**: Spare Bedroom  
**Office hours**: By appointment  


This course covers modern methods of handling longitudinal, repeated measures. The class will introduce the rationale of measuring change and stability over time to study phenomena, as well as how within-person designs can increase statistical power and precision compared to more traditional designs. Most the course will use multi-level models and latent (growth) curve models to specify patterns of change across time. Additional topics include: visualization, measurement invariance, time-to- event models and power. PREREQ: Use of R will be required, Familiarity with MLM and/or Structural Equation Models.


**Class textbook** 

Hoffman, Lesa. (2015). Longitudinal Analysis:Modeling Within-Person Fluctuation and Change. 

I have PDFs available if you do not want to purchase the textbook. 

I find this textbook quite readable, but if you are struggling with this textbook I have additional recommendations for MLM and longitudinal models that may fill in the gaps. Additionally, if there are topics that you are interested in and want to know more about please let me know as there are a number of textbooks devoted to a single topic. 


**Structure of class**

Each week will cover a specific type of longitudinal model. During Monday's class, I will provide an overview of the important considerations or motivation for this analysis. Wednesdays class will be more applied, devoted to walking through code and results and or introducing new packages. We'll call this the workshop portion.   

**Grading** 
Grading consists of 3 aspects: 

1. Semi-weekly "pop" quiz. Quizzes consist of 1-3 questions based on the previous lecture and readings. 

2. Homework take homes. Homework will be presented in the workshop portion (Wednesdays) of the class and due 1 week later. 

3. Final project. Everyone needs to do a longitudinal data analysis from start to finish. Preferably you have your own data, but if you do not then let me know and I can give you some. More details on this later. 

Grading breakdown is 1/3 for each of these components. 

**Schedule**

| Week | Date  |  Topic                      | Workshop             |  Readings |
-------|-------|------------------------------|----------------------|----------|
| 1    | 1/25   | Motivation, terms, concepts, and graphing     |  Data  | Ch 1-2 |
| 2    | 2/1    | MLM review and introduction to within person models  | lme4 | Ch 3,5| 
| 3    | 2/8    | Within person models  cont  |   |  Ch 4 - optional     | 
| 4    | 2/15   | Polynomial, piecewise and spline models |  plotting | Ch 6 |  
| 5    | 2/22   | Conditional growth models     |      | Ch 7 |
| 6    | 3/1    | Conditional growth models |   | Ch 8 | 
| 7    | 3/8   | Intensive data analysis/within person fluctuations | simulation |       |
| 8    | 3/15  | SEM and simple path models   |  lavaan       |  Ch 9   |  
| 9    | 3/22  |  SEM intro cont.  |  amelia            | 
| 10   | 3/29  | Latent (Grown) Curve Models  |   semPlot                 |  
| 11   | 4/5  |  2 measurement points    |  brms      |   
| 12   | 4/12   |  *Class canceled*     |             |                  
| 13   | 4/19  | Multiple group models |                 |
| 14   | 4/26  | Flexible SEM models (Latent-Change, STATE-TRAIT; ALT-SR)   |        |          
| 15   | 5/3  |  Mixture Models ??  |      |   

Other topics: Longitudinal mediation (and multilevel mediation), time to event analyses, power, ...?
